name: flutter_weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc:
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc:
  google_fonts:
  path_provider:
  hydrated_bloc:
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test:

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
